---
- name: Restore playbook.yml
  hosts: web1
  vars:
    firewall: firewalld
    
  tasks:
    # 1) 방화벽 닫기 - http, https
    # 2) 서비스 내리기 - firewalld, httpd
    # 3) 웹 서비스 설정 삭제 
    # * /var/www/html/index.html
    # 4) 패키지 삭제 - httpd, firewalld
    # 5) 팩트 삭제 - /etc/ansible/facts.d/

    - name: 1) 방화벽 내리기 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      with_items:
        - http
        - https
    - name: 3) 서비스 중지 - firewalld, httpd, mariadb
      service:
        name: "{{ item }}"
        state: stopped
        enabled: yes
      with_items:
        - firewalld
        - httpd
        - mariadb
      
    - name: 3) 웹 서비스 설정 삭제
      file:
        path: /var/www/html/index.html
        state: absent
    - name: 4) 패키지 삭제 - httpd, firewalld, mariadb-server
      yum:
        name:
          - http
          - firewalld
          - mariadb-server
        state: absent
    - name: 5) 팩트 삭제 - /etc/ansible/facts.d/
      file:
        path: /etc/ansible/facts.dest
        state: absent


    