---
- name: Restore the playbooks.
  hosts: all
  vars_files: vars.yml
  gather_facts: no
  tasks:
    - name: files 삭제 - /etc/pki/*, /var/www/html/*
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ ssl_dir }}"

    - name: 서비스 중지
      service: 
        name: "{{ item }}"
        state: stopped
        enabled: no
       with_items: "{{ services }}"
      ignore_errors: yes

    - name: 패키지 제거
      yum:
        name: "{{ packages }}"
        state: absent

    - name: 방화벽 중지
      firewalld:
        service: "{{ item }}"
        permanent: no
        immediate: no
        state: disabled
      with_items: "{{ fw_svcs }}"
