--- 
- name: playbook.yml 복원하기
  hosts: ansible1.example.com
  gather_facts: yes
  vars_files:
    - vars/vars.yml
  tasks: 
    # 1) 방화벽 내리기 - http, https
    - name: 1) 방화벽 내리기 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      with_items:
        - "{{ fw_http }}"
        - "{{ fw_https }}"
    # 2) 웹 서비스설정
    # 2-1) /etc/httpd/secrets/htpasswd (files/htpasswd)
    # * /etc/httpd/secrets 디렉토리 제거
    - name: 2-1) /etc/httpd/secrets/htpasswd (files/htpasswd) 
      file: 
        path: "{{ secrets_dir }}"
        state: absent
    # 2-2) /var/www/html/index.html (using the facts) 제거
    - name: 2-2) /var/www/html/index.html (using the facts) 제거
      file:
        path: "{{ web_root }}/index.html"
        state: absent
    # 2-3) /var/www/html/.htaccess (files/.htaccess) 제거
    - name: 2-3) /var/www/html/.htaccess (files/.htaccess) 제거
      file:
        path: "{{ htaccess_dest }}"
        state: absent
    # 3) 서비스 중지 - firewalld, httpd
    - name: 3) 서비스 중지 - firewalld, httpd
      service:
        name: "{{ item }}"
        state: stopped
        enabled: yes
      with_items:
        - "{{ svc_fw }}"
        - "{{ svc_web }}"
    # 1) 패키지 삭제 - firewalld, httpd, mod_ssl
    - name: 패키지 삭제 - firewalld, httpd, mod_ssl
      yum:
        name: 
          - "{{ pkg_fw }}"
          - "{{ pkg_http }}"
          - "{{ pkg_https }}"
        state: absent
