---
- name: WEB-DB service
  hosts: web1
  tasks:
    # 1) 패키지 설치 - Web(httpd, php, php-mysqlnd, php-pdo), db(mariadb-server), firewall(firewalld)
    # 2) Configure the web service - /var/www/html/index.php
    # 3) 서비스 기동 - firewall, web(httpd), db(mariadb-server)
    # 4) 방화벽 서비스 설정 - http, https 
    - name: 패키지 설치 - Web(httpd, php, php-mysqlnd, php-pdo), db(mariadb-server), firewall(firewalld)
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-pdo
          - mariadb-server
          - firewalld
        state: present
    - name: Configure the web service - /var/www/html/index.php
      get_url: 
        url: http://192.168.10.10/index.php
        dest: /var/www/html/index.php
    - name: 서비스 기동 - firewall, web(httpd), db(mariadb-server)
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb
    - name: 방화벽 서비스 설정 - http, https 
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https

- name: 웹 서버 테스트
  hosts: localhost
  tasks:
    - name: 웹 서버 연결
      uri: 
        url: http://web1.example.com
        return_content: yes
        status_code: 200


