---
- name: Retore the playbook.yml
  hosts: all
  vars_files: vars/vars.yml
  tasks: 
    - name: Close the port with firewalld module - {{ fw_http }}, {{ fw_https }}
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - "{{ fw_http }}"
        - "{{ fw_https }}"

    - name: Remove the file - /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: 서비스 중지 - {{ svc_fw }}, {{ svc_web }}
      service: 
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - "{{ svc_fw }}"
        - "{{ svc_web }}"

    - name: 페키지 삭제 - {{ pkg_http }}, {{ pkg_https }}, {{ pkg_phthon }}, {{ pkg_fw }}
      yum:
        name:
          - "{{ pkg_http }}"
          - "{{ pkg_https }}"
          - "{{ pkg_phthon }}"
          - "{{ pkg_fw }}"
        state: absent
