---
- name: postfix 설치
  yum:
    name: postfix
    state: latest
  tags:
    - server
  notify:
    - start_postfix
- name: dovecot 설치
  yum:  
    name: dovecot
    state: latest
  tags:
    - client
  notify:
    - start_dovecot

- name: Download main.cf configuration
  get_url:
    url: http://ansible.example.com/main.cf
    dest: /etc/postfix/main.cf
  tags:
    - server
  notify: 
    - restart_postfix
